/**
 * Build-time sync: fetch portfolio case studies + site content from Crelyst public API
 * and write generated TypeScript modules for the Vite app to import.
 *
 * Fails loudly on fetch errors — never writes empty/stale fallback data.
 */

import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECTS_OUTPUT = resolve(__dirname, '../src/data/projects.generated.ts');
const SITE_CONTENT_OUTPUT = resolve(__dirname, '../src/data/site-content.generated.ts');

const API_BASE = (
  process.env.CRELYST_API_URL ||
  process.env.VITE_CRELYST_API_URL ||
  'https://www.crelyst.com.ng'
).replace(/\/$/, '');

const MAX_ATTEMPTS = 3;
const TIMEOUT_MS = 15_000;

type ApiListResponse = {
  status: boolean;
  data?: {
    caseStudies: Array<{ slug: string } & Record<string, unknown>>;
  };
  message?: string;
};

type ApiDetailResponse = {
  status: boolean;
  data?: {
    caseStudy: Record<string, unknown>;
  };
  message?: string;
};

type ApiSiteContentResponse = {
  status: boolean;
  data?: {
    content: {
      about: Record<string, unknown>;
      contact: Record<string, unknown>;
      seo?: Record<string, unknown>;
      projectsListingSeo?: Record<string, unknown>;
    };
  };
  message?: string;
};

async function fetchWithRetry(url: string): Promise<Response> {
  let lastError: unknown;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

    try {
      const response = await fetch(url, {
        signal: controller.signal,
        headers: { Accept: 'application/json' },
      });
      clearTimeout(timer);

      if (!response.ok) {
        throw new Error(`HTTP ${response.status} ${response.statusText} for ${url}`);
      }

      return response;
    } catch (err) {
      clearTimeout(timer);
      lastError = err;
      if (attempt < MAX_ATTEMPTS) {
        const delay = attempt * 1000;
        console.warn(`[sync-content] attempt ${attempt} failed, retrying in ${delay}ms…`);
        await new Promise(r => setTimeout(r, delay));
      }
    }
  }

  throw lastError;
}

function stripAdminFields(caseStudy: Record<string, unknown>) {
  const {
    _id: _omitId,
    id: _omitDocId,
    isActive: _omitActive,
    displayOrder: _omitOrder,
    createdAt: _omitCreated,
    updatedAt: _omitUpdated,
    ...content
  } = caseStudy;
  return content;
}

function serializeProjectsFile(projects: Record<string, unknown>[]): string {
  const json = JSON.stringify(projects, null, 2);
  return `/**
 * AUTO-GENERATED by scripts/sync-content.ts — do not edit.
 * Source: Crelyst GET /api/public/portfolio-case-studies
 */
import type { Project, Paragraph, SectionHeading } from './projects';

export type { Project, Paragraph, SectionHeading };

export const projects: Project[] = ${json} as Project[];

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}

export function getAdjacentProjects(slug: string) {
  const idx = projects.findIndex((p) => p.slug === slug);
  const prev = idx > 0 ? projects[idx - 1] : projects[projects.length - 1];
  const next = idx < projects.length - 1 ? projects[idx + 1] : projects[0];
  return { prev, next };
}
`;
}

function serializeSiteContentFile(content: {
  about: Record<string, unknown>;
  contact: Record<string, unknown>;
  seo: Record<string, unknown>;
  projectsListingSeo: Record<string, unknown>;
}): string {
  const json = JSON.stringify(content, null, 2);
  return `/**
 * AUTO-GENERATED by scripts/sync-content.ts — do not edit.
 * Source: Crelyst GET /api/public/bbs-site-content
 */
import type { BbsSiteContent } from './site-content';

export type { BbsSiteContent };

export const siteContent: BbsSiteContent = ${json} as BbsSiteContent;
`;
}

async function syncProjects(): Promise<void> {
  console.log(`[sync-content] fetching from ${API_BASE}/api/public/portfolio-case-studies`);

  const listRes = await fetchWithRetry(`${API_BASE}/api/public/portfolio-case-studies?limit=100`);
  const listJson = (await listRes.json()) as ApiListResponse;

  if (!listJson.status || !listJson.data?.caseStudies?.length) {
    throw new Error(
      `[sync-content] list endpoint returned no case studies: ${listJson.message ?? 'unknown error'}`
    );
  }

  const slugs = listJson.data.caseStudies.map(c => String(c.slug));
  const projects: Record<string, unknown>[] = [];

  for (const slug of slugs) {
    const detailRes = await fetchWithRetry(
      `${API_BASE}/api/public/portfolio-case-studies/${encodeURIComponent(slug)}`
    );
    const detailJson = (await detailRes.json()) as ApiDetailResponse;

    if (!detailJson.status || !detailJson.data?.caseStudy) {
      throw new Error(
        `[sync-content] detail fetch failed for slug "${slug}": ${detailJson.message ?? 'unknown error'}`
      );
    }

    projects.push(stripAdminFields(detailJson.data.caseStudy));
  }

  mkdirSync(dirname(PROJECTS_OUTPUT), { recursive: true });
  writeFileSync(PROJECTS_OUTPUT, serializeProjectsFile(projects), 'utf8');
  console.log(`[sync-content] wrote ${projects.length} projects to ${PROJECTS_OUTPUT}`);
}

async function syncSiteContent(): Promise<void> {
  console.log(`[sync-content] fetching from ${API_BASE}/api/public/bbs-site-content`);

  const res = await fetchWithRetry(`${API_BASE}/api/public/bbs-site-content`);
  const json = (await res.json()) as ApiSiteContentResponse;

  if (!json.status || !json.data?.content?.about || !json.data?.content?.contact) {
    throw new Error(
      `[sync-content] site content endpoint returned incomplete data: ${json.message ?? 'unknown error'}`
    );
  }

  const content = {
    about: json.data.content.about,
    contact: json.data.content.contact,
    seo: json.data.content.seo ?? {},
    projectsListingSeo: json.data.content.projectsListingSeo ?? {},
  };

  mkdirSync(dirname(SITE_CONTENT_OUTPUT), { recursive: true });
  writeFileSync(SITE_CONTENT_OUTPUT, serializeSiteContentFile(content), 'utf8');
  console.log(`[sync-content] wrote site content to ${SITE_CONTENT_OUTPUT}`);
}

async function main(): Promise<void> {
  await syncProjects();
  await syncSiteContent();
}

main().catch(err => {
  console.error('[sync-content] FATAL:', err instanceof Error ? err.message : err);
  process.exit(1);
});
